project:
  type: book
  output-dir: docs

book:
  title: "algbio_book"
  reader-mode: true

  page-footer:
    right: |
      Конспекты занятий магистратуры МФТИ ФБМФ "Алгоритмическая биология"

  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/florenskaial118/Alg_Bio_book.git

  chapters:
  - index.qmd
  
  - part: "1 семестр"
    chapters:
      - Базы_данных_all.qmd
      - NGS_all.qmd
      - Интерпретация.qmd
      - Алгоритмы_HW.ipynb

  
  - part: "2 семестр"
    chapters:
      - алгоритмы_в_биоинформатике.qmd
      - машинка.qmd
      - медген.qmd
      - статистика_семинары.qmd
      - DevOps.qmd

bibliography: references.bib

highlight-style: pygments

format:
  html:
    theme:
      light: [cosmo, r4ds.scss]
      dark: [slate]
    code-link: true
    author-meta: "Флоренская Лидия"
    callout-appearance: simple

page-navigation: true
search: true